### ISSUE TITLE
OutOfMemory problem

### ISSUE THREAD

**Issue by DamjanZ** [nielsbasjes/yauaa#57] opened 2017-09-04 09:13 UTC
Hi,

I am using this User Agent parser for seven months and it was working great. But while I was watching logs I found part that contains OutOfMemoryError. The version is 1.0 and since I am using only certain fields, I did an UserAgentAnalyzer instance like this:
```
UserAgentAnalyzer uaa = UserAgentAnalyzer
                    .newBuilder()
                    .withoutCache()
                    .withField("OperatingSystemName")
                    .withField("OperatingSystemVersion")
                    .withField("DeviceName")
                    .hideMatcherLoadStats()
                    .build();
```
This is error that I receive:
> java.lang.OutOfMemoryError: Java heap space
> at java.util.Arrays.copyOf(Arrays.java:3332)
> at
> java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
> at
> java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:649)
> at java.lang.StringBuilder.append(StringBuilder.java:202)
> at
> nl.basjes.parse.useragent.analyze.MatcherAction.calculateInformPath(MatcherAction.java:397)
> at
> nl.basjes.parse.useragent.analyze.MatcherAction.calculateInformPath(MatcherAction.java:376)
> at
> nl.basjes.parse.useragent.analyze.MatcherAction.calculateInformPath(MatcherAction.java:397)
> at
> nl.basjes.parse.useragent.analyze.MatcherAction.calculateInformPath(MatcherAction.java:376)
> at
> nl.basjes.parse.useragent.analyze.MatcherAction.calculateInformPath(MatcherAction.java:397)
> at
> nl.basjes.parse.useragent.analyze.MatcherAction.calculateInformPath(MatcherAction.java:376)
> at
> nl.basjes.parse.useragent.analyze.MatcherAction.calculateInformPath(MatcherAction.java:397)
> at
> nl.basjes.parse.useragent.analyze.MatcherAction.calculateInformPath(MatcherAction.java:376)
> at
> nl.basjes.parse.useragent.analyze.MatcherAction.calculateInformPath(MatcherAction.java:397)
> at
> nl.basjes.parse.useragent.analyze.MatcherAction.calculateInformPath(MatcherAction.java:376)
> at
> nl.basjes.parse.useragent.analyze.MatcherAction.calculateInformPath(MatcherAction.java:397)
> at
> nl.basjes.parse.useragent.analyze.MatcherAction.calculateInformPath(MatcherAction.java:376)
> at
> nl.basjes.parse.useragent.analyze.MatcherAction.calculateInformPath(MatcherAction.java:397)
> at
> nl.basjes.parse.useragent.analyze.MatcherAction.calculateInformPath(MatcherAction.java:376)
> at
> nl.basjes.parse.useragent.analyze.MatcherAction.calculateInformPath(MatcherAction.java:397)
> at
> nl.basjes.parse.useragent.analyze.MatcherAction.calculateInformPath(MatcherAction.java:376)
> at
> nl.basjes.parse.useragent.analyze.MatcherAction.calculateInformPath(MatcherAction.java:397)
> at
> nl.basjes.parse.useragent.analyze.MatcherAction.calculateInformPath(MatcherAction.java:376)
> at
> nl.basjes.parse.useragent.analyze.MatcherAction.calculateInformPath(MatcherAction.java:369)
> at
> nl.basjes.parse.useragent.analyze.MatcherAction.calculateInformPath(MatcherAction.java:351)
> at
> nl.basjes.parse.useragent.analyze.MatcherAction.calculateInformPath(MatcherAction.java:336)
> at
> nl.basjes.parse.useragent.analyze.MatcherAction.registerAllPossiblyInterestingPatterns(MatcherAction.java:329)
> at
> nl.basjes.parse.useragent.analyze.MatcherAction.init(MatcherAction.java:212)
> at
> nl.basjes.parse.useragent.analyze.MatcherRequireAction.<init>(MatcherRequireAction.java:30)
> at nl.basjes.parse.useragent.analyze.Matcher.<init>(Matcher.java:142)
> at
> nl.basjes.parse.useragent.UserAgentAnalyzer.loadResources(UserAgentAnalyzer.java:219)
> at
> nl.basjes.parse.useragent.UserAgentAnalyzer.initialize(UserAgentAnalyzer.java:105)
> 
```

How can I fix this issue? Do I need to provide more information for this issue?

Thanks for your time.

**Comment by nielsbasjes** [comment] 2017-09-04 10:04
First of all I find it very nice to hear that people actually use this tool. So thank you.

You are the first report I got about running into an OOM.

Now the base system uses a few hundred MB of Ram for the data structures.
In addition the caching uses memory (which you have disabled).

So my questions to you:
1) How much memory does you application use and have.
2) What is your usage pattern / context? and why did you disable the caching?

In the mean while I'll do a check if there is a memory leak in the system.

**Comment by DamjanZ** [comment] 2017-09-04 12:36
No, thank you for making this library, since I couldn't find one that's frequently updated or not deprecated.
1, I'll have to check this one, since application uses Apache mod_proxy_balancer and filters request on different machines.
2. It is for the statistics purposes, since database saves data of user OS and Device. Honestly, I can't remember now why I disable it but maybe that's causing now the problem.

I'll try to set cache value, update to 2.0 version and let you know if there are any changes. And thanks for fast answer!

**Comment by nielsbasjes** [comment] 2017-09-04 12:56
I wrote a simple memory usage test to check ( see https://github.com/nielsbasjes/yauaa/blob/master/analyzer/src/test/java/nl/basjes/parse/useragent/TestPerformance.java#L59 ).

After a about 100000 iterations the memory usage only changes amounts in the 'few bytes' range.

```
14:42:55,345 [INFO ] TestPerformance                         :   52: After  125000 iterations and GC --> Used memory is  148474248 bytes (  141 MiB)
14:42:57,759 [INFO ] TestPerformance                         :   52: After  130000 iterations and GC --> Used memory is  148474248 bytes (  141 MiB)
14:43:00,139 [INFO ] TestPerformance                         :   52: After  135000 iterations and GC --> Used memory is  148474248 bytes (  141 MiB)
14:43:02,571 [INFO ] TestPerformance                         :   52: After  140000 iterations and GC --> Used memory is  148474248 bytes (  141 MiB)
14:43:04,987 [INFO ] TestPerformance                         :   52: After  145000 iterations and GC --> Used memory is  148474248 bytes (  141 MiB)
14:43:07,375 [INFO ] TestPerformance                         :   52: After  150000 iterations and GC --> Used memory is  148474248 bytes (  141 MiB)
14:43:09,811 [INFO ] TestPerformance                         :   52: After  155000 iterations and GC --> Used memory is  148474248 bytes (  141 MiB)
14:43:12,259 [INFO ] TestPerformance                         :   52: After  160000 iterations and GC --> Used memory is  148474248 bytes (  141 MiB)

```

I also had a closer look at your stack trace and this is a part of the initialization code. 
So this is what is done only once before the system can start analyzing useragents.
Because this must only be called once at the start of the application the OOM seems to be caused by the system simply not having enough memory available.

**Comment by nielsbasjes** [comment] 2017-09-04 14:59
Check this: When is a NEW instance of yauaa created?
If you have a fixed number then you'll be fine. If you create an instance for each new visitor then that is the problem you must change.

**Comment by DamjanZ** [comment] 2017-09-04 15:11
Yeah it's created for each visitor that logs into system. Since number isn't fixed, I'll change it to a single instance of UserAgentAnalyzer for project and create new instance of UserAgent for every user. Maybe that'll solve the problem.

**Comment by nielsbasjes** [comment] 2017-09-04 15:17
So looking at my memory stats this means that each visitor will give you a memory impact of ~100MB and 2-5 seconds unwanted startup time. Yes, this sounds like your problem.

**Comment by nielsbasjes** [comment] 2017-09-04 21:44
Good luck fixing your setup.
I'm closing this issue because it is not a bug in yauaa.

**Closed by nielsbasjes** 2017-09-04 21:44 UTC

**Comment by Lekha30** [comment] 2018-08-22 05:31
@DamjanZ , 
How did you fix up the issue you faced?

TIA

**Comment by DamjanZ** [comment] 2018-08-22 09:16
@Lekha30 
Like Niels suggested, single instance of object solved the problem.

**Comment by exabrial** [comment] 2019-11-18 16:18
Thank you for the great parsing library. But because the main entry point to the library is a `synchronized` method, you cannot do any parallel processing of user agent strings with the singleton.

**Comment by nielsbasjes** [comment] 2019-11-18 16:21
@exabrial That is correct. If you need to be able to do multiple in parallel consider using a pool of multiple instances.

**Comment by mdbyambaa** [comment] 2020-11-30 20:01
Thank you @nielsbasjes for your great library,

i was use it with Fast Object Pool library like and i haven't problem.

package mdb.CMN.System.Utilities.UA;

import javax.annotation.PostConstruct;
import javax.annotation.PreDestroy;
import javax.ejb.DependsOn;
import javax.ejb.Singleton;
import javax.ejb.Startup;

import cn.danielw.fop.ObjectFactory;
import cn.danielw.fop.ObjectPool;
import cn.danielw.fop.PoolConfig;
import mdb.CMN.Base.Constants.CMNBaseConstants.CMN.SETTING;
import mdb.CMN.System.Configure.CMNSystemConfigure;
import mdb.CMN.System.Constants.CMNSystemConstants;
import mdb.CMN.Utilities.Log.CMNLogUtilities;
import nl.basjes.parse.useragent.UserAgentAnalyzer;

/**
 *
 * @author Byambasuren.MD
 *
 */

@Startup
@DependsOn("CMNSystemConfigure")
@Singleton(name = "CMNSystemUAUtilities", mappedName = "CMNSystemUAUtilities")
public class CMNSystemUAUtilities implements CMNSystemConstants {

	private static CMNSystemUAUtilities INSTANCE;

	private static UserAgentAnalyzer ANALYZER;

	private static ObjectFactory<UserAgentAnalyzer> ANALYZER_POOL_FACTORY;

	private static ObjectPool<UserAgentAnalyzer> ANALYZER_POOL;

	/** Instances **/

	public static CMNSystemUAUtilities getInstance() {
		return INSTANCE != null ? INSTANCE : (INSTANCE = new CMNSystemUAUtilities());
	}

	/** Listener **/

	@PostConstruct
	public void init() {
		CMNSystemUAUtilities.INSTANCE = this;
		CMNSystemUAUtilities.ANALYZER = UserAgentAnalyzer.newBuilder().hideMatcherLoadStats().withCache(5000).build();

		CMNSystemUAUtilities.ANALYZER_POOL_FACTORY = new ObjectFactory<UserAgentAnalyzer>() {
			public UserAgentAnalyzer create() {
				return UserAgentAnalyzer.newBuilder().hideMatcherLoadStats().withCache(1000).build();
			}

			public void destroy(UserAgentAnalyzer o) {

			}

			public boolean validate(UserAgentAnalyzer o) {
				return true;
			}
		};

		CMNSystemUAUtilities.ANALYZER_POOL = new ObjectPool(new PoolConfig().setPartitionSize(CMNSystemConfigure.getInstance().getSetting(SYSTEM.SETTING.UA.UA_POOL_PARTITION_SIZE).getValueASInteger()).setMaxSize(CMNSystemConfigure.getInstance().getSetting(SYSTEM.SETTING.UA.UA_POOL_MAX_SIZE).getValueASInteger()).setMinSize(CMNSystemConfigure.getInstance().getSetting(SYSTEM.SETTING.UA.UA_POOL_MIN_SIZE).getValueASInteger()).setMaxIdleMilliseconds(60 * 1000 * CMNSystemConfigure.getInstance().getSetting(SYSTEM.SETTING.UA.UA_POOL_IDLE_TIME).getValueASInteger()), ANALYZER_POOL_FACTORY);
	}

	@PreDestroy
	public void destroy() {
		try {
			CMNSystemUAUtilities.ANALYZER_POOL.shutdown();
		} catch (Exception ex) {
			CMNLogUtilities.error(CMNSystemConfigure.getInstance().getSetting(SETTING.LOG.SYSTEM).getValue(), "[UA.Utilities][Error on shutDown UA.Analyzer.Pool]");
		}
		CMNLogUtilities.info(CMNSystemConfigure.getInstance().getSetting(SETTING.LOG.SYSTEM).getValue(), "[UA.Utilities]");
	}

	/** Getter **/

	public UserAgentAnalyzer getAnalyzer() {
		return ANALYZER != null ? ANALYZER : (ANALYZER = UserAgentAnalyzer.newBuilder().hideMatcherLoadStats().withCache(5000).build());
	}

	public UserAgentAnalyzer getAnalyzerPool() {
		return CMNSystemUAUtilities.ANALYZER_POOL.borrowObject().getObject();
	}

}
