### ISSUE TITLE
Mac OS showing as Play Station.  Not a play station.

### ISSUE THREAD

**Issue by gloeffelholz** [nielsbasjes/yauaa#43] opened 2017-06-30 16:13 UTC
Background:
Looking at the OS field of bid_request_data ('$.us.dv.os') I noticed that from a random sample of 10K bids in the desktop channel on 6/27, ~13% of these had the value of 'PLAY_STATION' which seemed way too high.
Looking at the UA string from lineitem_scarcity_score ('$.ua') , most of these indicated that they were some version of OSX (e.g. macintosh; intel mac os x_10_15).
I've attached a dist from AML of 1 hour looking at all the cases where we saw a 'PLAY_STATION' OS type. Most of the time, the UA string indicates that the device has some kind of macintosh OS.

**Comment by nielsbasjes** [comment] 2017-06-30 17:08
Do you have concrete examples? I can only evaluate what you are saying with actual examples.

**Comment by nielsbasjes** [comment] 2017-07-03 09:11
@gloeffelholz You write you have attached something. Yet I do not see anything. Can you please attach what you intended to share?

**Comment by nielsbasjes** [comment] 2017-07-11 08:52
You have not provided me with anything to reproduce the unwanted effects you seem to have.
So for now I'm closing this as 'Not reproducable'.
Please reopen if you have more information.

**Closed by nielsbasjes** 2017-07-11 08:52 UTC
