### ISSUE TITLE
Issue loading resources (classloaders)

### ISSUE THREAD

**Issue by timclipsham** [nielsbasjes/yauaa#104] opened 2018-08-06 06:01 UTC
I've been trialing your library to parse user agents inside an Atlassian Confluence Server plugin, but I'm having difficulty getting it to work due to resource loading. I receive the error below when building the UserAgentAnalyzer class (using the sample code in the README).

`nl.basjes.parse.useragent.analyze.InvalidParserConfigurationException: Unable to find ANY config files`

It looks like the problem is related to the approach used to load the resources. The resource loading isn't using the class loader, and I also can't specify one.
https://github.com/nielsbasjes/yauaa/blob/master/analyzer/src/main/java/nl/basjes/parse/useragent/UserAgentAnalyzerDirect.java#L234

For example, in general within our app...
```java
// this doesn't work
this.getClass().getResource("UserAgents/Amazon.yaml");

// this works!
this.getClass().getClassLoader().getResource("UserAgents/Amazon.yaml");
```

**Comment by nielsbasjes** [comment] 2018-08-06 13:16
Thanks for reporting this. I'll get on this later this week.
Do you know of a way for me to verify if the changes I'm going to make are correct? 
I.e. how can I write an automated test for this?

**Comment by nielsbasjes** [comment] 2018-08-06 19:38
I found this that seems to be relevant:
https://stackoverflow.com/questions/676250/different-ways-of-loading-a-file-as-an-inputstream

My knowledge on classloading is limited so I'm in doubt which is the correct classloader 
`this.getClass().getClassLoader()`
or
`Thread.currentThread().getContextClassLoader()`

**Comment by nielsbasjes** [comment] 2018-08-06 22:27
I had a look inside Spring to see which classloader it was using.
Turns out it was already doing exactly what is described in the mentioned stackoverflow post: 

1. Thread.currentThread().getContextClassLoader()
1. ClassUtils.class.getClassLoader()
1. ClassLoader.getSystemClassLoader()

Now I assume that in your case the  this.getClass().getClassLoader() results in something different.
So what I did is that only if there are no results then a second attempt is made using the this.getClass().getClassLoader().

I put this fix in a separate branch https://github.com/nielsbasjes/yauaa/tree/ClassLoadingFix
I have also build a 5.1-SNAPSHOT version that has been uploaded in this repository https://oss.sonatype.org/content/repositories/snapshots/

So just put this in your pom.xml and you should be able to try this fix in your code.
```
  <repositories>
    <repository>
      <id>sonatype-snapshots</id>
      <releases><enabled>false</enabled></releases>
      <snapshots><enabled>true</enabled></snapshots>
      <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
    </repository>
  </repositories>
```

Please let me know if this fixes things for you.

**Comment by timclipsham** [comment] 2018-08-09 02:17
Thanks for the quick turnaround and response! 👍 Sorry it took me so long to get back to you.

Unfortunately I'm not an expert either. I tried the changes in 5.1-SNAPSHOT but didn't have any luck, however after a whole day of research and debugging, I've come to learn some more about the problem itself.

### Context
We're creating a plugin inside Atlassian Confluence. These plugins are OSGi Bundles, and it looks like Confluence under the hood uses the Apache Felix (an open source implementation of OSGi) to manage the plugins and their dependencies. With regards to class loaders, each plugin installed in Confluence is in effect sandboxed with its own class loader, which allows different plugins to use different versions of the same dependencies internally, and also import other dependencies from within Confluence itself or even from other plugins.

### The bigger problem
Firstly, the PathMatchingResourcePatternResolver class fundamentally is unable to load a resource from a OSGi bundle, when running on Apache Felix. It has inbuilt workarounds for the Equinox implementation of OSGi, but not for the Apache Felix implementation. Unfortunately, we can't switch that out on our side because it's part of Confluence itself, which we build upon.

This same issue is seen here, but doesn't appear to have a solution.
https://jira.spring.io/browse/SPR-6019

Secondly, even when I put forward our best effort to workaround PathMatchingResourcePatternResolver, by dropping all default resources and adding just one back that avoids the "classpath" & wildcard syntax, it still fails to load that resource further down in `loadResource` when it attempts to get an input stream, although I'm not sure why at this stage.

### Further technical details
Internally PathMatchingResourcePatternResolver resolves the path before the first wildcard, then traverses the (sometimes virtual) file system to match the wildcard rules. In this case, the path `classpath*:UserAgents/**/*.yaml` is initially resolved to look up "UserAgents/" using getResource, which succeeds in our environment with a URL of `bundle://{some_internal_reference}/UserAgents/`. Eventually PathMatchingResourcePatternResolver doesn't have a way to handle a `bundle://` protocol and instead falls back to trying to traverse this as if it's directly on the file system, which it's probably not, and throws a FileNotFoundException. 0 results are returned in `loadResources`.

---

Do you have any thoughts? (and did the details above make any sense?)

**Comment by nielsbasjes** [comment] 2018-08-13 22:31
Sorry for the late reply.
I have read your explanation and I think I understand what you are explaining.
At this point my knowledge of OSGi is too limited to understand how this should be fixed.
Looking at the Spring issue you found I tend to think this is something that should be fixed there.
Even so, If you can provide me with a way to reproduce this locally here in my IDE (I use IntelliJ) then I'm willing to have another look at it.

**Comment by timclipsham** [comment] 2018-08-13 23:56
No problem. I had a pretty thorough look through to propose some solutions, but in the end they all looked quite involved, and for the immediate customer need we opted for a basic string check in the interim.

I expect in the future we'll revisit this because we want to properly distinguish all robot traffic. I'll reach out again when we do with some more specifics. This library seemed the best for robot detection from the few I tried.

Thanks again @nielsbasjes for your help. Feel free to close this out for now, if that's more practical.

**Comment by nielsbasjes** [comment] 2018-08-20 22:48
Just out of curiosity; can you share a small part of your code that does only 1 thing: Reproduce the problem? I suspect that a basic OSGi setup that simply includes my stuff can show the problem so I can understand what is going on.

**Comment by timclipsham** [comment] 2018-09-11 03:29
Sure, let me have a go and see if I can put something together. The OSGi setup isn't handled specifically by our app/plugin, it's set up by the host product, however I don't think it'll be too difficult to create a standalone example that reproduces it.

**Comment by nielsbasjes** [comment] 2018-11-21 20:52
@timclipsham If you have a way for me to reproduce this then please reopen this issue.
I have been unable to setup a OSGi setup.

**Closed by nielsbasjes** 2018-11-21 20:52 UTC
