### ISSUE TITLE
 Error reading resources: JAR entry Alcatel.yaml not found in ...

### ISSUE THREAD

**Issue by Meemaw** [nielsbasjes/yauaa#216] opened 2020-07-22 13:38 UTC
Hi! I'm trying to use this library in a Gradle (Quarkus) project and I'm having some issues.

Dependency was included as follows:
```
dependencies {
    implementation 'nl.basjes.parse.useragent:yauaa:5.18'
    ....
}
```

Stack trace:
```java
Caused by: nl.basjes.parse.useragent.analyze.InvalidParserConfigurationException: Error reading resources: JAR entry Alcatel.yaml not found in /Users/matejsnuderl/.gradle/caches/modules-2/files-2.1/nl.basjes.parse.useragent/yauaa/5.18/642850ffc08301cc6e91dfba39b8a7c517367165/yauaa-5.18.jar
	at nl.basjes.parse.useragent.AbstractUserAgentAnalyzerDirect.loadResources(AbstractUserAgentAnalyzerDirect.java:384)
	at nl.basjes.parse.useragent.AbstractUserAgentAnalyzerDirect$AbstractUserAgentAnalyzerDirectBuilder.lambda$build$1(AbstractUserAgentAnalyzerDirect.java:1535)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
	at nl.basjes.parse.useragent.AbstractUserAgentAnalyzerDirect$AbstractUserAgentAnalyzerDirectBuilder.build(AbstractUserAgentAnalyzerDirect.java:1535)
	at nl.basjes.parse.useragent.AbstractUserAgentAnalyzer$AbstractUserAgentAnalyzerBuilder.build(AbstractUserAgentAnalyzer.java:153)
	at com.meemaw.session.useragent.service.UserAgentService.init(UserAgentService.java:21)
	at com.meemaw.session.useragent.service.UserAgentService_Bean.create(UserAgentService_Bean.zig:144)
	at com.meemaw.session.useragent.service.UserAgentService_Bean.create(UserAgentService_Bean.zig:160)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:88)
	at io.quarkus.arc.impl.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:99)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.getValue(ComputingCache.java:41)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:25)
	at com.meemaw.session.useragent.service.UserAgentService_ClientProxy.arc$delegate(UserAgentService_ClientProxy.zig:110)
	at com.meemaw.session.useragent.service.UserAgentService_ClientProxy.parse(UserAgentService_ClientProxy.zig:259)
	at com.meemaw.session.pages.service.PageService.createPageAndNewSession(PageService.java:79)
	at com.meemaw.session.pages.service.PageService.createPage(PageService.java:55)
	at com.meemaw.session.pages.service.PageService_Subclass.createPage$$superaccessor2(PageService_Subclass.zig:489)
	at com.meemaw.session.pages.service.PageService_Subclass$$function$$2.apply(PageService_Subclass$$function$$2.zig:47)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.smallrye.metrics.interceptors.TimedInterceptor.timedCallable(TimedInterceptor.java:95)
	at io.smallrye.metrics.interceptors.TimedInterceptor.timedMethod(TimedInterceptor.java:70)
	at io.smallrye.metrics.interceptors.TimedInterceptor_Bean.intercept(TimedInterceptor_Bean.zig:366)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:50)
	at io.opentracing.contrib.interceptors.OpenTracingInterceptor.wrap(OpenTracingInterceptor.java:92)
	at io.opentracing.contrib.interceptors.OpenTracingInterceptor_Bean.intercept(OpenTracingInterceptor_Bean.zig:411)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at com.meemaw.session.pages.service.PageService_Subclass.createPage(PageService_Subclass.zig:442)
	at com.meemaw.session.pages.service.PageService_ClientProxy.createPage(PageService_ClientProxy.zig:276)
	at com.meemaw.session.sessions.resource.v1.SessionResourceImpl.createPage(SessionResourceImpl.java:41)
	at com.meemaw.session.sessions.resource.v1.SessionResourceImpl_Subclass.createPage$$superaccessor1(SessionResourceImpl_Subclass.zig:223)
	at com.meemaw.session.sessions.resource.v1.SessionResourceImpl_Subclass$$function$$1.apply(SessionResourceImpl_Subclass$$function$$1.zig:47)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.hibernate.validator.runtime.interceptor.AbstractMethodValidationInterceptor.validateMethodInvocation(AbstractMethodValidationInterceptor.java:69)
	at io.quarkus.hibernate.validator.runtime.interceptor.MethodValidationInterceptor.validateMethodInvocation(MethodValidationInterceptor.java:17)
	at io.quarkus.hibernate.validator.runtime.interceptor.MethodValidationInterceptor_Bean.intercept(MethodValidationInterceptor_Bean.zig:340)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at com.meemaw.session.sessions.resource.v1.SessionResourceImpl_Subclass.createPage(SessionResourceImpl_Subclass.zig:176)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:167)
	... 65 more
Caused by: java.io.FileNotFoundException: JAR entry Alcatel.yaml not found in /Users/matejsnuderl/.gradle/caches/modules-2/files-2.1/nl.basjes.parse.useragent/yauaa/5.18/642850ffc08301cc6e91dfba39b8a7c517367165/yauaa-5.18.jar
	at java.base/sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:147)
	at java.base/sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:155)
	at nl.basjes.shaded.org.springframework.core.io.UrlResource.getInputStream(UrlResource.java:173)
	at nl.basjes.parse.useragent.AbstractUserAgentAnalyzerDirect.loadResources(AbstractUserAgentAnalyzerDirect.java:381)
	... 112 more
```

**Comment by nielsbasjes** [comment] 2020-07-22 15:21
Just to double check: The jar file (the one on maven central) does have this file related to the error.
```
$ unzip -l ~/.m2/repository/nl/basjes/parse/useragent/yauaa/5.18/yauaa-5.18.jar | fgrep Alcatel
     5413  2020-06-17 12:31   UserAgents/Alcatel.yaml
```
The first thing I do notice is that the error states `Alcatel.yaml` but the actual file is located in a subdirectory `UserAgents` but that may be nothing serious.

Looking at the Quarkus website apparently they essentially do lot's of smart stuff to make things move faster.
So I suspect changes in classloading and loading resources from classes.

Now I think my library should be compatible (apparently it currently is not) yet I have no experience with Quarkus.
So what I would like is to have a minimal (maven based) example that shows the problem, so I can make this part of the normal build cycle.

Do you have such a basic example for me?
Please.

**Comment by Meemaw** [comment] 2020-07-22 15:34
```sh
git clone git@github.com:Meemaw/quarkus-yauaa.git
cd quarkus-yauaa
mvn quarkus:dev
```

Visit http://localhost:8080/hello

**Comment by nielsbasjes** [comment] 2020-07-22 16:07
Awesome! Thanks. Fully reproducible error.
I put together a similar thing with Quarkus that somehow does not show this error:
https://github.com/nielsbasjes/yauaa/tree/master/examples/quarkus

**Comment by Meemaw** [comment] 2020-07-23 14:03
Any idea what is the change that made it work?

**Comment by nielsbasjes** [comment] 2020-07-23 14:09
I added a line of code to show which resource it is trying to load.
Insights so far:
The ones that DO work
- My quarkus module inside the project directory structure
`file [/home/nbasjes/workspace/yauaa/analyzer/target/classes/UserAgents/Alcatel.yaml]`
- The existing webservlet
`URL [jar:file:/home/nbasjes/.m2/repository/nl/basjes/parse/useragent/yauaa/5.19-SNAPSHOT/yauaa-5.19-SNAPSHOT.jar!/UserAgents/Alcatel.yaml]`

The ones that DO NOT work:
-  Both your and my Quarkus servlet outside the project directory structure:
`URL [jar:file:/home/nbasjes/.m2/repository/nl/basjes/parse/useragent/yauaa/5.19-SNAPSHOT/yauaa-5.19-SNAPSHOT.jar!/Alcatel.yaml]`

The important difference here is the missing subdirectory from which the file should be loaded.
So the first thing I noticed about your report (the missing directory) seems to be an important indicator here.

At this point it seems like a bug in the Spring method I use to resolve the dependencies in combination with Quarkus.

If you have any idea what may cause this please let me know.

**Comment by nielsbasjes** [comment] 2020-07-23 16:12
I was able to fully reproduce this problem in a new project: https://github.com/nielsbasjes/BugReport-SpringQuarkus-ResourceLoading

At this point I'm concluding that this is a problem of the combination of the Spring PathMatchingResourcePatternResolver that does not work correctly when used within Quarkas.
So this is a bug that I'm currently not able to fix myself; I'll submit a bug report to Quarkas.

**Comment by nielsbasjes** [comment] 2020-07-23 17:38
I am unsure if this problem is a SpringFramework, a Quarkus or perhaps  in the combination of the two.
So I have submitted this problem to both projects: 
- https://github.com/quarkusio/quarkus/issues/10943
- https://github.com/spring-projects/spring-framework/issues/25465

**Comment by nielsbasjes** [comment] 2020-07-23 19:10
New insight:
This does NOT work: 
- mvn quarkus:dev

This does seem to work:
- mvn clean package
- java -jar target/quarkus-5.19-SNAPSHOT-runner.jar
- http://localhost:8080/parse

**Comment by nielsbasjes** [comment] 2020-07-23 20:47
Which changes into this if you run it really outside of the main project tree ...

Does NOT work:
- `mvn clean package`
- `mvn quarkus:dev`

Does work:
- `mvn clean package -DskipTests=true`
  `java -jar target/yauaa-example-quarkus-*-runner.jar`

- `mvn clean package -DskipTests=true -Pnative -Dquarkus.native.container-build=true`
  `./target/yauaa-example-quarkus-*-runner`

For the last one I had to make some minor changes to the Yauaa base code.

**Comment by nielsbasjes** [comment] 2020-07-24 09:36
I created a workaround that may work well enough.
Just now I uploaded 5.19-SNAPSHOT  to  https://oss.sonatype.org/content/repositories/snapshots/
Can you please verify this in your system?

**Comment by Meemaw** [comment] 2020-07-24 10:40
Seems to work -- added in this PR: https://github.com/insights-io/Insight/pull/304. I'll wait for a proper release (if you plan to release this) before I merge it.

**Comment by nielsbasjes** [comment] 2020-07-24 12:29
I released 5.19 with this workaround so you can continue with your project.
   https://repo1.maven.org/maven2/nl/basjes/parse/useragent/yauaa/5.19/
I'm leaving this issue open for now so it is easier to track in conjunction with the actual bug in Quarkus.

**Comment by Meemaw** [comment] 2020-07-24 12:43
Great, thank you for being so proactive and responsive! 👍

**Comment by nielsbasjes** [comment] 2020-07-28 12:30
The upstream bug report a Quarkus has been fixed and is probably part of their next release.
Since I already included a usable workaround I'm now closing this is resolved.

**Closed by nielsbasjes** 2020-07-28 12:30 UTC
Labels: Waiting for external dependency, bug
