### ISSUE TITLE
Inconstancy of builder API

### ISSUE THREAD

**Issue by ncoquelet** [nielsbasjes/yauaa#66] opened 2017-11-16 12:34 UTC
If I create an analyzer instance with builder like this, this works as except :
`UserAgentAnalyzer analyzer = UserAgentAnalyzer.newBuilder().withField("DeviceClass").withoutCache().build();`

But if I move the withoutCache() call at the beginning, the API contract isn't the same and a nocache instance is return.
`UserAgentAnalyzer analyzer = UserAgentAnalyzer.newBuilder().withoutCache().withField("DeviceClass").build();`

This break my eclipse compilation.

**Comment by nielsbasjes** [comment] 2017-11-16 12:42
I did some quick tests by manually inspecting these two instances and I have not been able to find any difference between them.

    UserAgentAnalyzer analyzer1 = UserAgentAnalyzer.newBuilder().withField("DeviceClass").withoutCache().build();
    UserAgentAnalyzer analyzer2 = UserAgentAnalyzer.newBuilder().withoutCache().withField("DeviceClass").build();

What version are you using?

**Comment by ncoquelet** [comment] 2017-11-17 11:02
Hi,
I'm using the version 3.1
The stranger thing is when I compile my code with the jdk in maven, I don't get an error.
But in Eclipse, if I place withField() after withoutCache(), it return an UserAgentAnalyzerDirectBuilder instead of UserAgentAnalyzerBuilder, so the build() return an UserAgentAnalyzerDirect instance.

**Comment by nielsbasjes** [comment] 2017-11-17 20:13
That is very strange. 
All methods in the Builder return a value of the type specified in the generic, which the class from which you called the static method newBuilder. 
So this effect you describe should not occur.
I'm using IntelliJ IDEA and there I do not have any problems like this.

At this point I'm guessing you found a bug in Eclipse caused by this type of use of generics. 

Can you please try this with a different IDE? Perhaps Netbeans or IntelliJ?

**Comment by nielsbasjes** [comment] 2017-11-19 09:59
Please also check if your Eclipse is using the same version of Java you use when running on the commandline.

**Comment by nielsbasjes** [comment] 2017-11-20 11:29
I have filed a bug report with the Eclipse project.
https://bugs.eclipse.org/bugs/show_bug.cgi?id=527475

**Comment by nielsbasjes** [comment] 2017-11-20 12:23
Thank you for reporting this.

I checked this code against the Java 1.8 compiler, IntelliJ (latest), NetBeans 8.1 and the latest Eclipse.

Only Eclipse shows this problem.
So I filed a bug report with the Eclipse project and I documented this problem in the README.md of this project.

The workaround: Use a different IDE until Eclipse fixes this.

I'm closing this report because there is no problem with this project.

**Closed by nielsbasjes** 2017-11-20 12:23 UTC
