### ISSUE TITLE
Error getting certain values 

### ISSUE THREAD

**Issue by MaksNikitaMaks** [nielsbasjes/yauaa#426] opened 2022-01-13 08:52 UTC
Good afternoon.
Sorry for my english.
Why is it that when I set up a library to get certain values, I get completely different results?
For example, there is the following line 
"_Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36 Edg/96.0.1054.2_"
**The following parameters are set in the program** 
```
        UserAgentAnalyzer uaa = UserAgentAnalyzer
                .newBuilder()
                .withField("DeviceBrand")
                .build();
```
as a result, I get not **DeviceBrand** but **DeviceClass**, why? Why do I get only DeviceClass, without DeviceBrand, I did everything according to the instructions.

If I get all values, then there will be no error, but I need to get only certain values

**Comment by nielsbasjes** [comment] 2022-01-13 15:42
I tried the above code with the useragent you provided.
When I retrieve the "DeviceBrand" I get the correct value: "Unknown".
Can you please provide more info what is going wrong?

**Comment by MaksNikitaMaks** [comment] 2022-01-14 05:07
Here is a screenshot of my problem, since I'm from another country, I couldn't think of anything easier than throwing it in the readme

[problem](https://github.com/MaksNikitaMaks/Info)

If I don't select certain values, then everything will work correctly and DeviceBrand will indeed have the value "unknown" but I need to select only a few values and not all

**Comment by OranShuster** [comment] 2022-01-17 11:43
This also happens to me with `OperatingSystemVersion`
with the following user agent `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36`

When uaa is initialized like this
```
        this.userAgentAnalyzer = UserAgentAnalyzer
                .newBuilder()
                .hideMatcherLoadStats()
                .withCache(10000)
                .withFields("AgentName", "AgentVersionMajor", "OperatingSystemVersion", "OperatingSystemName")
                .build();
```
`uaa.parse(userAgent).getValue("OperatingSystemVersion")` -> "??"
when initialised without `withFields` it returns 10.15.7  correctly

**Comment by nielsbasjes** [comment] 2022-01-17 14:59
@OranShuster You are referring to a different situation; on Chrome 90+ the version of MacOS is fake so Yauaa reports it (since version 6.3) as "??". 
See https://bugs.chromium.org/p/chromium/issues/detail?id=1175225
https://github.com/nielsbasjes/yauaa/blob/master/analyzer/src/main/resources/UserAgents/GoogleChromeFrozen.yaml#L222

Also I cannot reproduce Yauaa to return `10.15.7` (which would be a bug because the right answer is `??`).

**Comment by OranShuster** [comment] 2022-01-17 15:12
@nielsbasjes i reran my tests again with version 6.2
for the user agent above it will return OperatingSystemVersion == `10.15`

But since this is a chrome bug we will just have to handle it on our side

**Comment by nielsbasjes** [comment] 2022-01-18 22:24
@OranShuster Yes, that was the bug that was fixed in 6.3

**Comment by nielsbasjes** [comment] 2022-01-18 22:26
@MaksNikitaMaks 
Fixed it.
https://github.com/nielsbasjes/yauaa/blob/master/analyzer/src/test/java/nl/basjes/parse/useragent/TestUseragent.java#L437

**Closed by nielsbasjes** 2022-01-18 22:26 UTC
Labels: bug

**Comment by OranShuster** [comment] 2022-01-18 22:39
@nielsbasjes 
Just a quick question if you don't mind - 
Looking at the unit test and comments I understand that DeviceBrand is derived from AgentInformationUrl and AgentInformationEmail?
Are those relations mentioned in the docs?
I think that most users will assume that a field dependencies are added when that field is requested. Is there a plan to add such behaviour?
Verified that with these settings we are actually getting DeviceBrand
```
        UserAgentAnalyzer uaa = UserAgentAnalyzer
                .newBuilder()
                .hideMatcherLoadStats()
                .withFields(DEVICE_BRAND,AGENT_INFORMATION_URL,AGENT_INFORMATION_EMAIL)
                .withoutCache()
                .build();
```

**Comment by nielsbasjes** [comment] 2022-01-18 23:13
The `DeviceBrand` is extracted from many things and if those do not give a suitable result then the domain name in the URL and Email are used as fall back.
If you ask for the `DeviceBrand` then the `AgentInformationUrl` and `AgentInformationEmail` will be added automatically because they are dependencies needed for the field you requested.

So in your example you only need this:

    .withFields(DEVICE_BRAND)

**Comment by OranShuster** [comment] 2022-01-18 23:23
@nielsbasjes 
I had to reread the OP and look at your comments again to figure out I didn't understand the issue completely.
Thanks for putting up with odd unrelated questions
