### ISSUE TITLE
problems if the useragent-string has software/app infos

### ISSUE THREAD

**Issue by ts-1u1** [nielsbasjes/yauaa#227] opened 2020-12-30 10:30 UTC
I found a problem with this useragents since yauaa 5.18
Since yauaa version 5.18 we've had problems if the useragent-string has software/app infos.

- test:
    input:
      user_agent_string: 'Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; tb-gmx/2.7.8; (gmx/1.4.0.0); rv:11.0) like Gecko'
    expected:
      AgentClass  : 'Browser'
      AgentName  : 'Internet Explorer'
      AgentVersion  : '11.0'
      AgentVersionMajor  : '11'
      AgentNameVersion  : 'Internet Explorer 11.0'
      AgentNameVersionMajor  : 'Internet Explorer 11'

**Comment by nielsbasjes** [comment] 2020-12-31 00:15
This does not look like a normal internet explorer. To me this seems like an application of some sorts has taken over. 

So my question is what was the exact setup that created this useragent?

**Comment by ts-1u1** [comment] 2021-01-04 10:06
We get requests from an outdated browser app with this user agent .
Another user agent string is
 'Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; Touch; rv:11.0; BR-Safe-Browsing) like Gecko', 
We don't know anything about the setup.
We only need the agent name and the version '11.0 ' info.  With yauaa  5.17 everything works correctly.

**Comment by nielsbasjes** [comment] 2021-01-04 23:29
The first case example (with the tb-gmx) is almost identical to what I've had in the code as a test case here https://github.com/nielsbasjes/yauaa/blob/master/analyzer/src/main/resources/UserAgents/SpecialBrowsers.yaml#L2589

Note that I realized long ago that the result of IE 11 was wrong as you can still see from the comment I put in: 

    # TODO: Review this. tb-gmx is the real useragent. Perhaps this is Thunderbird via gmx.net free email website in Germany ??

Last June I fixed this problem and as a consequence you are now seeing `AgentNameVersion : 'TB-GMX 2.6.12'` which I think is the best possible result I can get from this.
The other example (with the `BR-Safe-Browsing`) follows roughly the same pattern as the `tb-gmx` case and as a consequence you get a similar effect: `AgentNameVersion : 'BR-Safe-Browsing ??'`

So in 5.17 is was not working correctly, now it is working a lot better.

So in both cases you have software or an app that created this useragent: This means the AgentName is **NOT** `Internet Explorer` and the version is **NOT** `11.0`.

It would be really helpful if you can please give me information what really created these useragents (i.e. what app, browser, plugin, device, ...).

Until then I'm sticking to the best guess I have which is the addition that was added by the tool that created these strings.

**Comment by ts-1u1** [comment] 2021-01-05 13:18
thank you for your effort, unfortunately we have no information about the setup.
we use 5.17, which works for our application.
maybe you want to have a look, this parser also provides the correct information
https://developers.whatismybrowser.com/

**Comment by nielsbasjes** [comment] 2021-01-05 13:42
Because these are clearly manipulated useragents that indicate they have been created by `something else` this analyzer (now) reports them as being the `something else` agent instead of `Internet Explorer` (which would be an incorrect result).

You however want to have it to report the incorrect `Internet Explorer` instead.
If you really want that you can do that by adding your own rules to the system and override the correct result with the result that you want to hear (i.e. Trumping).  

Something like this seems to work on my machine right now
```
- matcher:
    require:
      - 'agent.(1)product.(1)comments.entry.(1)product.(1)name="Trident"^.version="7.0"'
    extract:
      - 'AgentName    : 2010 : "Internet Explorer"'
      - 'AgentVersion : 2010 : agent.(1)product.comments.entry.(1)keyvalue.key="rv"^.value'
```
Do note that this will also break the results for many other browsers too, not just the two examples you reported. 

I'm closing this as not a bug.

**Closed by nielsbasjes** 2021-01-05 13:42 UTC
