### ISSUE TITLE
Maven dependency not working

### ISSUE THREAD

**Issue by abhinavoorja** [nielsbasjes/yauaa#78] opened 2018-04-12 08:51 UTC
Description	Resource	Path	Location	Type
Missing artifact nl.basjes.parse.useragent:yauaa:jar:4.2	pom.xml	/utils	line 274	Maven Dependency Problem

<dependency>
			<groupId>nl.basjes.parse.useragent</groupId>
			<artifactId>yauaa</artifactId>
			<version>4.2</version>
</dependency>

**Comment by nielsbasjes** [comment] 2018-04-12 09:04
I have cleared my local ~/.m2 , updated a project of mine and build it.

It uses maven and has
```
<dependency>
  <groupId>nl.basjes.parse.useragent</groupId>
  <artifactId>yauaa</artifactId>
  <version>4.2</version>
</dependency>
```
During the build I see 

```
Downloading: https://repo.maven.apache.org/maven2/nl/basjes/parse/useragent/yauaa/4.2/yauaa-4.2.pom
Downloaded: https://repo.maven.apache.org/maven2/nl/basjes/parse/useragent/yauaa/4.2/yauaa-4.2.pom (10 kB at 37 kB/s)
Downloading: https://repo.maven.apache.org/maven2/nl/basjes/parse/useragent/yauaa-parent/4.2/yauaa-parent-4.2.pom
Downloaded: https://repo.maven.apache.org/maven2/nl/basjes/parse/useragent/yauaa-parent/4.2/yauaa-parent-4.2.pom (16 kB at 1.4 MB/s)
Downloading: https://repo.maven.apache.org/maven2/nl/basjes/parse/useragent/yauaa/4.2/yauaa-4.2.jar
Downloaded: https://repo.maven.apache.org/maven2/nl/basjes/parse/useragent/yauaa/4.2/yauaa-4.2.jar (1.4 MB at 16 MB/s)
```

This is a problem in your systems/code.
Closing this as "Not a bug".

**Closed by nielsbasjes** 2018-04-12 09:04 UTC
