### ISSUE TITLE
I hit from safari with linux operating system but showed chromium as agent name

### ISSUE THREAD

**Issue by aruntanwar3** [nielsbasjes/yauaa#32] opened 2017-03-09 13:25 UTC
I found a problem with this useragent.
[Please update the output below to match what you expect it should be]

```

- test:
    input:
      user_agent_string: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.100 Safari/537.36'
    expected:
      DeviceClass  : 'Desktop'
      DeviceName  : 'Linux Desktop'
      DeviceBrand  : 'Unknown'
      DeviceCpu  : 'Intel x86_64'
      OperatingSystemClass  : 'Desktop'
      OperatingSystemName  : 'Linux'
      OperatingSystemVersion  : 'Intel x86_64'
      OperatingSystemNameVersion  : 'Linux Intel x86_64'
      LayoutEngineClass  : 'Browser'
      LayoutEngineName  : 'Blink'
      LayoutEngineVersion  : '54.0'
      LayoutEngineVersionMajor  : '54'
      LayoutEngineNameVersion  : 'Blink 54.0'
      LayoutEngineNameVersionMajor  : 'Blink 54'
      AgentClass  : 'Browser'
      AgentName  : 'Chrome'
      AgentVersion  : '54.0.2840.100'
      AgentVersionMajor  : '54'
      AgentNameVersion  : 'Chrome 54.0.2840.100'
      AgentNameVersionMajor  : 'Chrome 54'



```

**Comment by nielsbasjes** [comment] 2017-03-09 16:51
Looking at the Apple website and https://en.m.wikipedia.org/wiki/Safari_(web_browser) I concluded that Safari doesn't exist.
So what Linux distribution are you running and where can I download Safari for Linux?

**Comment by nielsbasjes** [comment] 2017-03-10 12:20
I had another look and Safari really does NOT exist for Linux.
If you really think you have Safari then my best guess is that you have been fooled by someone into believing that Chrome is Safari.
They may even have improved your "Safari for Linux" with some unexpected virus/trojan/ransom software.

I'm closing this as "Not a bug"

**Closed by nielsbasjes** 2017-03-10 12:20 UTC
